import { test, expect, type Page } from '@playwright/test'
import { CAST, CLUES, ENDINGS, PLACES, PUZZLES, SCENES, SIDE_SCENES, STORY_REQUIREMENTS } from '../../src/lib/aphelion/definition'

test.use({ actionTimeout: 15_000 })
const settled = (page: Page) => expect(page.getByRole('main')).toHaveAttribute('aria-busy', 'false', { timeout: 20_000 })
async function readingMode(page: Page) {
  await page.getByRole('button', { name: '航程设置', exact: true }).click()
  await page.getByRole('checkbox', { name: /文字探索/ }).check()
  await page.getByRole('checkbox', { name: /整幕阅读/ }).check()
  await page.keyboard.press('Escape')
}
async function closeStory(page: Page) {
  const close = page.getByRole('button', { name: '暂时结束交谈', exact: true })
  if (await close.isVisible()) await close.click()
}
async function travel(page: Page, key: string) {
  await settled(page)
  const title = PLACES.find(place => place.key === key)!.title
  if ((await page.locator('.ap-location').innerText()).includes(title)) return
  await closeStory(page)
  await page.getByRole('button', { name: /甲板地图/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: new RegExp(title) }).click()
  await expect(page.locator('.ap-location')).toContainText(title, { timeout: 30_000 })
  await settled(page)
}

test('科幻游戏完整主线、三组联锁、离线与步骤恢复、分支结局和日志', async ({ page }, testInfo) => {
  test.setTimeout(420_000)
  const errors: string[] = [], external: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/^https?:/.test(request.url())) { const host = new URL(request.url()).hostname; if (!['127.0.0.1','localhost','fonts.googleapis.com','fonts.gstatic.com'].includes(host)) external.push(request.url()) } })
  await page.route(/^https:\/\/fonts\.(googleapis|gstatic)\.com\//, route => route.abort())
  await page.goto('play/aphelion')
  await expect(page.getByRole('heading', { name: '远日点', exact: true })).toBeVisible()
  await expect(page.locator('.ap-canvas canvas')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('title-desktop.png') })
  await page.getByRole('button', { name: '结束冷眠' }).click()
  await expect(page.getByRole('button', { name: /^与沈迩交谈/ })).toBeVisible({ timeout: 90_000 })
  await page.screenshot({ path: testInfo.outputPath('station-desktop.png') })
  await travel(page, 'comms')
  await readingMode(page)
  await page.context().setOffline(true)
  const firstBranches: Record<string,string> = { s08:'route.audit', s16:'route.water', s24:'route.people' }
  const route = SCENES.flatMap(scene => firstBranches[scene.key] ? [scene, SIDE_SCENES.find(side => side.key === firstBranches[scene.key])!] : [scene])
  for (const scene of route) {
    const clue = CLUES.find(item => item.key === STORY_REQUIREMENTS[scene.key])
    if (clue) {
      await closeStory(page)
      await travel(page, clue.place)
      await page.getByRole('button', { name: clue.title, exact: true }).click()
      const puzzle = PUZZLES.find(item => item.clue === clue.key)
      if (puzzle) {
        const panel = page.getByRole('dialog', { name: puzzle.title })
        await panel.getByRole('button', { name: puzzle.steps[2], exact: true }).click()
        await expect(panel).toContainText('顺序没有通过设备联锁')
        await panel.getByRole('button', { name: puzzle.steps[0], exact: true }).click()
        await settled(page)
        await expect(panel.getByRole('button', { name: puzzle.steps[0], exact: true })).toBeDisabled()
        if (clue.key === 'timestamp') {
          await page.keyboard.press('Escape')
          await page.context().setOffline(false)
          await page.reload()
          await page.getByRole('button', { name: '继续航程', exact: true }).click()
          await settled(page)
          await page.context().setOffline(true)
          await page.getByRole('button', { name: clue.title, exact: true }).click()
          await expect(panel).toContainText('已恢复之前完成的设备步骤')
          await expect(panel.getByRole('button', { name: puzzle.steps[0], exact: true })).toBeDisabled()
        }
        for (const step of puzzle.steps.slice(1)) { await panel.getByRole('button', { name: step, exact: true }).click(); await settled(page) }
        await expect(panel).not.toBeVisible()
      }
      await settled(page)
      await expect(page.getByRole('button', { name: clue.title, exact: true })).not.toBeVisible()
    }
    await travel(page, scene.place)
    if (!(await page.getByRole('region', { name: '剧情对话' }).isVisible())) await page.getByRole('button', { name: new RegExp(`^与${CAST[scene.speaker].name}交谈`) }).click()
    await expect(page.locator('.ap-dialogue header')).toContainText(scene.title)
    if (scene.key !== 's40') { await page.locator('.ap-choices button').first().click(); await settled(page) }
    if (scene.key.startsWith('s') && (scene.order + 1) % 4 === 0) console.info(`远日点界面：第 ${scene.chapter + 1} 章`)
  }
  await expect(page.locator('.ap-choices button')).toHaveCount(4)
  await closeStory(page)
  await page.getByRole('button', { name: '存档', exact: true }).click()
  await page.getByRole('button', { name: '保存当前检查点', exact: true }).click()
  await settled(page)
  await page.getByRole('button', { name: /^与饶舒交谈/ }).click()
  await page.locator('.ap-choices').getByRole('button', { name: new RegExp(ENDINGS[0].title) }).click()
  await settled(page)
  await expect(page.locator('.ap-dialogue header')).toContainText(ENDINGS[0].title)
  await page.screenshot({ path: testInfo.outputPath('ending-desktop.png') })
  await page.getByRole('button', { name: '回看航程', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('已核验 8 / 8 条证据')
  await expect(page.getByRole('dialog').locator('details')).toHaveCount(44)
  for (const unseen of ['站长的临时权限','多出来的十二秒','交付清单之外']) await expect(page.getByRole('dialog').locator('summary', { hasText: unseen })).toHaveCount(0)
  await page.context().setOffline(false)
  await page.reload()
  await page.getByRole('button', { name: '继续航程', exact: true }).click()
  await settled(page)
  await expect(page.locator('.ap-mission')).toContainText(ENDINGS[0].title)
  await page.getByRole('button', { name: '存档', exact: true }).click()
  await page.getByRole('button', { name: '从这里重走', exact: true }).click()
  await settled(page)
  await page.getByRole('button', { name: /^与饶舒交谈/ }).click()
  await page.locator('.ap-choices').getByRole('button', { name: new RegExp(ENDINGS[1].title) }).click()
  await settled(page)
  await expect(page.locator('.ap-dialogue')).toContainText('核心区域的持续功率随之降到零')
  expect(errors).toEqual([])
  expect(external).toEqual([])
})

test('科幻游戏手机操作、逐句阅读、设置保留当前台词与进度', async ({ page }, testInfo) => {
  test.setTimeout(150_000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('play/aphelion')
  await expect(page.getByRole('heading', { name: '远日点', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('title-mobile.png') })
  await page.getByRole('button', { name: '结束冷眠' }).click()
  await expect(page.getByRole('button', { name: '向前', exact: true })).toBeVisible({ timeout: 90_000 })
  await page.getByRole('button', { name: /^与沈迩交谈/ }).click()
  await page.locator('.ap-next').click()
  const line = await page.locator('.ap-beat p').innerText()
  await page.getByRole('button', { name: '航程设置', exact: true }).click()
  await page.getByRole('checkbox', { name: /轻量画面/ }).check()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.ap-beat p')).toHaveText(line)
  await page.screenshot({ path: testInfo.outputPath('dialogue-mobile.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '展开本幕', exact: true }).click()
  await page.locator('.ap-choices button').first().click()
  await settled(page)
  await page.reload()
  await page.getByRole('button', { name: '继续航程', exact: true }).click()
  await settled(page)
  await readingMode(page)
  await travel(page, 'med')
  await page.getByRole('button', { name: /^与沈迩交谈/ }).click()
  await expect(page.locator('.ap-dialogue header')).toContainText(SCENES[1].title)
})

test('文字开放世界三款作品入口独立，科幻三维地图可到达十个区域并保留显示偏好', async ({ page }) => {
  test.setTimeout(210_000)
  await page.goto('openworld')
  await expect(page.getByRole('link', { name: '游玩内置游戏：潮痕，最后一盏灯' })).toHaveAttribute('href', '/storyforge/play/tidemark')
  await page.getByRole('link', { name: '游玩内置游戏：远日点，第七码头' }).click()
  await page.getByRole('button', { name: '航程设置', exact: true }).click()
  await page.getByRole('checkbox', { name: /轻量画面/ }).check()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '结束冷眠' }).click()
  await expect(page.getByRole('button', { name: /^与沈迩交谈/ })).toBeVisible({ timeout: 90_000 })
  for (const place of [...PLACES.slice(1), PLACES[0]]) await travel(page, place.key)
  await readingMode(page)
  await page.reload()
  await page.getByRole('button', { name: '继续航程', exact: true }).click()
  await settled(page)
  await expect(page.locator('.ap-location')).toContainText('第七码头')
  await expect(page.locator('.ap-canvas')).toHaveCount(0)
  await page.getByRole('button', { name: '航程设置', exact: true }).click()
  for (const name of [/轻量画面/, /文字探索/, /整幕阅读/]) await expect(page.getByRole('checkbox', { name })).toBeChecked()
  await page.goto('play/tidemark')
  await expect(page.getByRole('heading', { name: '最后一盏灯', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '继续旅程', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '游戏设置', exact: true }).click()
  for (const name of [/轻量画面/, /文字探索/, /展开本幕对话/]) await expect(page.getByRole('checkbox', { name })).not.toBeChecked()
  await page.goto('play/aphelion')
  await page.getByRole('button', { name: '继续航程', exact: true }).click()
  await settled(page)
  await expect(page.locator('.ap-location')).toContainText('第七码头')
})
