import { test, expect } from '@playwright/test'

test('old power links and the origin tab edit the same records and preserve focused drafts', async ({ page }, info) => {
  await page.route('https://fonts.googleapis.com/**', route => route.abort())
  await page.goto('./')
  const ids = await page.evaluate(async () => {
    const imp = new Function('p', 'return import(p)')
    const { createWorkspace } = await imp('/storyforge/src/lib/workspace/create-workspace.ts')
    const { useWorldviewStore } = await imp('/storyforge/src/stores/worldview.ts')
    const { db } = await imp('/storyforge/src/lib/db/schema.ts')
    const { project } = await createWorkspace({ name: '力量入口合并验收', description: '', genres: [], status: 'drafting', targetWordCount: 100000 }, { kind: 'novel', novelProfile: 'long' })
    const store = useWorldviewStore.getState()
    await store.loadAll(project.id)
    await store.saveWorldview({ projectId: project.id, powerHierarchy: '概述保留：潮汐力量有代价。' })
    await store.savePowerSystem({ projectId: project.id, name: '潮息体系', description: '规则明细保留', levels: '听潮\n归海', rules: '每次借潮必须付出记忆' })
    return { projectId: project.id, powerId: (await db.powerSystems.where('projectId').equals(project.id).first()).id }
  })
  await page.goto(`./workspace/${ids.projectId}?module=power-system`)
  await expect(page.getByRole('group', { name: '力量体系规则明细' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '世界与设定三级导航' }).getByRole('button', { name: '力量体系', exact: true })).toHaveCount(0)
  await expect(page.getByText('概述保留：潮汐力量有代价。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'AI 生成', exact: true }).filter({ visible: true })).toHaveCount(1)
  const details = page.getByRole('group', { name: '力量体系规则明细' })
  await details.getByText('每次借潮必须付出记忆', { exact: true }).click()
  await details.locator('textarea').fill('修改后的禁忌：不得借取明日之潮')
  // Switch while still focused: the shared draft barrier must save the rules.
  await page.getByRole('button', { name: '世界来源', exact: true }).click()
  await expect(page).toHaveURL(/originField=origin/)
  await page.getByRole('button', { name: '力量体系', exact: true }).click()
  await expect(page).toHaveURL(/originField=power/)
  await expect(details).toContainText('修改后的禁忌：不得借取明日之潮')
  await page.reload()
  await expect(details).toContainText('修改后的禁忌：不得借取明日之潮')
  const stored = await page.evaluate(async ids => {
    const { db } = await new Function('p', 'return import(p)')('/storyforge/src/lib/db/schema.ts')
    return { rules: await db.powerSystems.get(ids.powerId), count: await db.powerSystems.where('projectId').equals(ids.projectId).count(), overview: (await db.worldviews.where('projectId').equals(ids.projectId).first()).powerHierarchy }
  }, ids)
  expect(stored.count).toBe(1)
  expect(stored.rules.levels).toBe('听潮\n归海')
  expect(stored.rules.rules).toBe('修改后的禁忌：不得借取明日之潮')
  expect(stored.overview).toBe('概述保留：潮汐力量有代价。')
  await page.screenshot({ path: info.outputPath('unified-power-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(details).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('world-engine power links share the origin editor and preserve its selected tab', async ({ page }) => {
  await page.goto('./world/worlds')
  await page.getByRole('button', { name: '新建世界', exact: true }).click()
  await page.getByLabel('新世界名称').fill('统一力量世界')
  await page.getByRole('button', { name: '创建世界', exact: true }).click()
  await expect(page).toHaveURL(/world\/basics\?project=\d+/)
  const projectId = new URL(page.url()).searchParams.get('project')!
  await page.goto(`./world/basics?project=${projectId}&module=power-system`)
  const details = page.getByRole('group', { name: '力量体系规则明细' })
  await expect(details).toBeVisible()
  await expect(page.getByRole('navigation', { name: '世界内容导航' }).getByRole('button', { name: '力量体系', exact: true })).toHaveCount(0)
  await details.getByText('修炼条件、突破瓶颈、禁忌…', { exact: true }).click()
  await details.locator('textarea').fill('世界规则必须留存')
  await page.getByRole('button', { name: '世界来源', exact: true }).click()
  await expect(page).toHaveURL(/world\/basics\?.*originField=origin/)
  await page.getByRole('button', { name: '力量体系', exact: true }).click()
  await expect(page).toHaveURL(/world\/basics\?.*originField=power/)
  await page.reload()
  await expect(details).toContainText('世界规则必须留存')
})
