import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Link } from 'react-router'
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Compass, Eye, Headphones, Map, MessageCircle, RotateCcw, Save, Settings2, VolumeX, X } from 'lucide-react'
import { useAdventureGamePlayerStore } from '../stores/adventure-game-player'
import { builtinAdventureSessions } from '../lib/builtin-adventure/player'
import { useAphelionPlayer } from '../lib/aphelion/use-player'
import { ALL_SCENES, CAST, CHAPTERS, CLUES, ENDINGS, PLACES, PUZZLES, type CastKey } from '../lib/aphelion/definition'
import { createAphelionScene, type AphelionScene } from '../lib/aphelion/scene'
import '../components/text-game/aphelion.css'

type Game=ReturnType<typeof useAphelionPlayer>
function Panel({title,onClose,children}:{title:string;onClose():void;children:ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{const element=ref.current;element?.showModal();return()=>element?.close()},[])
  return <dialog ref={ref} className="ap-panel" aria-label={title} onCancel={event=>{event.preventDefault();onClose()}}><header><div><small>APHELION / 航程记录</small><h2>{title}</h2></div><button aria-label="关闭面板" onClick={onClose}><X size={19}/></button></header>{children}</dialog>
}
function StationCanvas({game:g}:{game:Game}) {
  const host=useRef<HTMLDivElement>(null),callbacks=useRef(g);callbacks.current=g
  useEffect(()=>{
    if(!host.current)return
    let active=true,arrival=Promise.resolve(),scene:AphelionScene|undefined
    try {
      scene=createAphelionScene(host.current,{initialPlace:g.place.key,preview:!g.playing,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,
        onNearby:place=>callbacks.current.setNearby(place),onInteract:()=>callbacks.current.interact(),onFailure:message=>callbacks.current.failure(message),
        onArrive:place=>{const sessionId=useAdventureGamePlayerStore.getState().selectedSessionId;arrival=arrival.then(async()=>{const store=useAdventureGamePlayerStore.getState();if(!active||store.selectedSessionId!==sessionId)return;const current=store.runtimeState.adventure?.currentLocationKey;if(current&&current!==place)await store.act(`move.${current}.${place}`)}).catch(problem=>{if(active)callbacks.current.failure(problem instanceof Error?problem.message:'地点保存失败')})},
      });g.api.current=scene
    }catch(problem){g.failure(problem instanceof Error?problem.message:'无法创建三维画面，已切换到文字探索。')}
    return()=>{active=false;scene?.dispose();g.api.current=null}
    // The mounted canvas owns its renderer; reactive controls use the scene API.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])
  useEffect(()=>g.api.current?.setPaused(Boolean(g.busy||g.panel||g.story||g.puzzle)),[g.busy,g.panel,g.story,g.puzzle,g.api])
  useEffect(()=>g.api.current?.setQuality(g.display.low),[g.display.low,g.api])
  useEffect(()=>g.api.current?.setQuest(g.objective.key,g.required?g.objective.npc:g.scene.speaker),[g.objective,g.scene.speaker,g.required,g.api])
  useEffect(()=>g.api.current?.setEnding(g.finished),[g.finished,g.api])
  return <div ref={host} className="ap-canvas"/>
}
function useStationSound() {
  const context=useRef<AudioContext|null>(null),[enabled,setEnabled]=useState(false)
  useEffect(()=>()=>{void context.current?.close()},[])
  useEffect(()=>{const visibility=()=>{if(document.hidden)void context.current?.suspend();else if(enabled)void context.current?.resume()};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[enabled])
  const toggle=()=>{if(context.current){void context.current.close();context.current=null;setEnabled(false);return}const audio=new AudioContext();context.current=audio;const master=audio.createGain();master.gain.value=.025;master.connect(audio.destination);[65.41,98,130.81,164.81].forEach((frequency,index)=>{const tone=audio.createOscillator(),gain=audio.createGain(),lfo=audio.createOscillator(),depth=audio.createGain();tone.frequency.value=frequency;gain.gain.value=.12;depth.gain.value=.06;lfo.frequency.value=.025+index*.006;tone.connect(gain);gain.connect(master);lfo.connect(depth);depth.connect(gain.gain);tone.start();lfo.start()});setEnabled(true)}
  return{enabled,toggle}
}
function StationMap({game:g}:{game:Game}) {
  return <><div className="ap-map"><svg viewBox="0 0 360 400" role="img" aria-label="远日点十个区域的空间站地图"><g fill="none" stroke="#2d586b" strokeWidth="12">{[-20,0,20].map(z=><path key={z} d={`M 60 ${230+z*3.7} H 300`}/>)}{[-24,0,24].map(x=><path key={x} d={`M ${180+x*5} 304 V 156`}/>)}<path d="M 180 156 V 82"/></g>{PLACES.map((place,index)=><g key={place.key} className={place.key===g.objective.key?'is-objective':''}><rect x={180+place.x*5-35} y={230+place.z*3.7-23} width="70" height="46" rx="4" fill={place.key===g.place.key?'#1b5666':'#0e2435'} stroke={place.key===g.objective.key?'#e9c88c':'#48778b'}/><text x={180+place.x*5} y={226+place.z*3.7} textAnchor="middle" fill="#a7c2d1" fontSize="8">{String(index+1).padStart(2,'0')}</text><text x={180+place.x*5} y={241+place.z*3.7} textAnchor="middle" fill="#e0ebed" fontSize="9">{place.title}</text></g>)}</svg><small>前往标记地点，或在三维场景中自由行走</small></div><div className="ap-destinations">{PLACES.map((place,index)=><button key={place.key} disabled={g.busy||!g.playing} onClick={()=>g.go(place.key)}><span className="ap-number">{String(index+1).padStart(2,'0')}</span><span>{place.title}<small>{place.key===g.objective.key?'当前调查目标':place.key===g.place.key?'当前所在区域':place.description}</small></span>{place.key===g.place.key?<Check size={16}/>:<ChevronRight size={16}/>}</button>)}</div></>
}
function Journal({game:g}:{game:Game}) {
  const visited=g.narrative?.visitedNodeKeys??[]
  return <><p className="ap-intro">{g.finished?`${g.ending?.title} · ${g.ending?.subtitle}`:'将已观测的事实与尚未证实的推测分开。'}<small>已核验 {CLUES.filter(clue=>g.hasItem(clue.key)).length} / {CLUES.length} 条证据</small></p><h3>原始证据</h3><div className="ap-evidence">{CLUES.map(clue=><article key={clue.key} className={g.hasItem(clue.key)?'is-found':''}><small>{PLACES.find(place=>place.key===clue.place)?.title}</small><h4>{g.hasItem(clue.key)?clue.title:'尚未核验'}</h4><p>{g.hasItem(clue.key)?clue.description:'随调查推进，新的证据会在对应区域解锁。'}</p></article>)}</div><h3>已签署的决定</h3>{g.narrative?.choiceHistory.filter(choice=>{const entry=g.manifest?.narrative.choices.find(item=>item.choiceKey===choice.choiceKey);return entry&&!entry.text.startsWith('继续')}).map((choice,index)=>{const entry=g.manifest?.narrative.choices.find(item=>item.choiceKey===choice.choiceKey);return <article className="ap-history" key={index}><strong>{entry?.text}</strong><p>{entry?.description}</p></article>})}<h3>亲历的航程</h3>{visited.map(key=>{const scene=ALL_SCENES.find(item=>item.key===key)??ENDINGS.find(item=>item.key===key);return scene&&<details key={key}><summary>{scene.title}</summary>{g.manifest?.narrative.beats.filter(beat=>beat.nodeKey===key).map(beat=><p key={beat.beatKey}>{beat.speakerKey&&<b>{CAST[beat.speakerKey as CastKey]?.name}：</b>}{beat.text}</p>)}</details>})}</>
}
function SavePanel({game:g}:{game:Game}) {
  const [automatic,setAutomatic]=useState(false)
  return <><p className="ap-intro">调查、设备操作与剧情选择自动保存。检查点会开启一条新的航程，原记录保留。</p><button className="ap-primary" disabled={g.busy||!g.playing} onClick={()=>void g.run(async()=>{await g.store.saveCheckpoint(`${g.scene.title} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`);g.setPanel(null)})}><Save size={16}/>保存当前检查点</button><button className="ap-text-button" onClick={()=>setAutomatic(value=>!value)}>{automatic?'收起':'显示'}自动恢复点</button>{g.store.checkpoints.filter(point=>automatic||!point.name.startsWith('自动 · ')).map(point=><article className="ap-save" key={point.id}><div><strong>{PLACES.reduce((name,place)=>name.replace(` · ${place.key} · `,` · ${place.title} · `),point.name)}</strong><small>{new Date(point.createdAt).toLocaleString('zh-CN')}</small></div><button disabled={g.busy} onClick={()=>g.fork(point.id!)}><RotateCcw size={15}/>从这里重走</button></article>)}<h3>我的航程</h3>{builtinAdventureSessions(g.store.sessions,g.releaseId??-1).map(session=><button className="ap-session" disabled={g.busy||session.id===g.store.selectedSessionId} key={session.id} onClick={()=>g.select(session.id!)}><span>{session.title}<small>{new Date(session.updatedAt).toLocaleString('zh-CN')}</small></span>{session.id===g.store.selectedSessionId?<Check size={16}/>:<ArrowRight size={16}/>}</button>)}</>
}

export default function AphelionPage() {
  const g=useAphelionPlayer(),sound=useStationSound(),dialogue=useRef<HTMLElement|null>(null)
  const beat=g.beats[g.reading],readAll=g.display.fullText||g.reading>=g.beats.length-1
  const evidence=CLUES.filter(clue=>g.hasItem(clue.key)).length
  useEffect(()=>{const panel=dialogue.current?.querySelector('.ap-lines');if(panel)panel.scrollTop=0},[g.narrative?.currentNodeKey])
  const puzzle=PUZZLES.find(item=>item.clue===g.puzzle)
  return <main className={`ap-game ${g.playing?'ap-playing':'ap-title'}`} aria-busy={g.busy}>
    {!g.display.fallback&&<StationCanvas key={g.playing?`play-${g.store.selectedSessionId}`:'preview'} game={g}/>}
    <div className="ap-atmosphere"/>
    <header className="ap-topbar"><Link to="/openworld" aria-label="返回文字开放世界"><ArrowLeft size={16}/><span>文字开放世界</span></Link><span className="ap-wordmark">APHELION <i/> STATION 07</span><div><button aria-label={sound.enabled?'关闭环境音':'开启环境音'} onClick={sound.toggle}>{sound.enabled?<Headphones size={18}/>:<VolumeX size={18}/>}</button><button aria-label="航程设置" disabled={g.busy} onClick={()=>g.setPanel('settings')}><Settings2 size={18}/></button></div></header>
    {!g.playing?<section className="ap-title-content"><div className="ap-kicker"><i/> STORYFORGE ORIGINAL / 02</div><h1>远日点</h1><h2>第七码头</h2><p className="ap-title-copy">星光要走十七年。<br/>你的遗言，只提前了四十七分钟。</p><div className="ap-title-buttons">{g.hasSave&&<button className="ap-primary" disabled={g.busy} onClick={()=>void g.start(false)}>继续航程<ArrowRight size={17}/></button>}<button className={g.hasSave?'ap-secondary':'ap-primary'} disabled={g.busy} onClick={()=>void g.start(true)}>{g.installing?'正在准备航程…':'结束冷眠'}<ArrowRight size={17}/></button></div>{(g.loading||g.installing)&&<p className="ap-progress" role="status">{g.loading?'正在查找航程记录…':g.progress}</p>}<div className="ap-facts"><span><b>10</b>章主线</span><span><b>3</b>组设备谜题</span><span><b>4</b>种结局</span></div><p className="ap-content-note">一段关于预测、距离与归途的深空悬疑。<br/>可离线游玩 · 无阅读倒计时 · 包含失亲与生存决策主题</p></section>:<>
      <aside className="ap-mission"><div className="ap-kicker">值班记录 / {String(g.scene.chapter+1).padStart(2,'0')} OF 10</div><h2>{g.finished?g.ending?.title:CHAPTERS[g.scene.chapter]}</h2><button disabled={g.busy} onClick={()=>g.finished?g.setPanel('journal'):g.go(g.objective.key)}><span className="ap-target-dot"/><span>{g.finished?'航程已记录':g.required?`核验：${g.required.title}`:g.scene.title}<small>{g.finished?'打开日志，回看你留下的决定':`${g.objective.title} · ${g.required?'调查设备与原始证据':`与${CAST[g.scene.speaker].name}交谈`}`}</small></span><ChevronRight size={17}/></button><div className="ap-chapter-track">{CHAPTERS.map((chapter,index)=><i key={chapter} className={index<=g.scene.chapter?'active':''}/>)}</div></aside>
      <nav className="ap-toolbar" aria-label="航程工具"><button aria-label="甲板地图" title="甲板地图" disabled={g.busy} onClick={()=>g.setPanel('map')}><Map size={19}/><span>甲板地图</span><kbd>M</kbd></button><button aria-label="航程日志" title="航程日志" disabled={g.busy} onClick={()=>g.setPanel('journal')}><BookOpen size={19}/><span>航程日志</span><small>{evidence}/8</small></button><button aria-label="存档" title="存档" disabled={g.busy} onClick={()=>g.setPanel('saves')}><Save size={19}/><span>存档</span></button></nav>
      <div className="ap-location"><span>{String(PLACES.findIndex(place=>place.key===g.place.key)+1).padStart(2,'0')}</span><div><small>APHELION STATION</small><strong>{g.place.title}</strong></div><i/></div>
      {g.display.fallback&&!g.story&&<section className="ap-text-explore"><Compass size={32}/><div className="ap-kicker">文字探索</div><h2>{g.place.title}</h2><p>{g.place.description}</p><button className="ap-secondary" onClick={()=>g.setPanel('map')}>前往其他区域<ArrowRight size={16}/></button></section>}
      {!g.story&&!g.panel&&!g.puzzle&&<div className="ap-bottom"><div className="ap-controls"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>移动 / E 交谈<br/>点击地面行走 · 右键拖动转向</span></div><div className="ap-actions">{(g.atQuest||g.finished)&&<button className="ap-primary" disabled={g.busy} onClick={g.interact}><MessageCircle size={17}/>{g.finished?'阅读结局':`与${CAST[g.scene.speaker].name}交谈`}<kbd>E</kbd></button>}{CLUES.filter(clue=>clue.place===g.place.key&&g.atPlace&&!g.hasItem(clue.key)&&g.narrative?.variables[`unlocked_${clue.key}`]===true).map(clue=><button className="ap-secondary" disabled={g.busy} key={clue.key} onClick={()=>g.inspect(clue.key)}><Eye size={16}/>{clue.title}</button>)}</div><div className="ap-saved"><i/>记录随行动保存</div></div>}
      {!g.story&&!g.panel&&!g.puzzle&&!g.display.fallback&&<div className="ap-touch" aria-label="触屏方向控制">{[{label:'向前',x:0,z:-1,s:'↑'},{label:'向左',x:-1,z:0,s:'←'},{label:'向后',x:0,z:1,s:'↓'},{label:'向右',x:1,z:0,s:'→'}].map(direction=><button key={direction.label} aria-label={direction.label} disabled={g.busy} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);g.api.current?.setInput(direction.x,direction.z)}} onPointerUp={()=>g.api.current?.setInput(0,0)} onPointerCancel={()=>g.api.current?.setInput(0,0)}>{direction.s}</button>)}</div>}
      {g.story&&<section ref={dialogue} className={`ap-dialogue ${g.display.fullText?'ap-expanded':''}`} aria-label="剧情对话"><header><div><small>{g.finished?'航程终点':CHAPTERS[g.scene.chapter]}</small><h2>{g.finished?g.ending?.title:g.scene.title}</h2></div><div><button className="ap-text-button" onClick={()=>g.setDisplay(value=>({...value,fullText:!value.fullText}))}>{g.display.fullText?'逐句阅读':'展开本幕'}</button><button aria-label="暂时结束交谈" disabled={g.busy} onClick={()=>g.setStory(false)}><X size={18}/></button></div></header>{g.display.fullText?<div className="ap-lines">{g.beats.map(line=><p key={line.beatKey} className={line.kind==='dialogue'?'is-dialogue':''}>{line.speakerKey&&<b style={{color:CAST[line.speakerKey as CastKey]?.color}}>{CAST[line.speakerKey as CastKey]?.name}</b>}{line.text}</p>)}</div>:<div className="ap-beat" key={beat?.beatKey}>{beat?.speakerKey&&<div className="ap-speaker" style={{color:CAST[beat.speakerKey as CastKey]?.color}}>{CAST[beat.speakerKey as CastKey]?.name}<small>{CAST[beat.speakerKey as CastKey]?.role}</small></div>}<p>{beat?.text}</p></div>}<footer><small>{g.display.fullText?`${g.beats.length} 段记录`:`${String(g.reading+1).padStart(2,'0')} / ${g.beats.length}`}</small>{!readAll?<button className="ap-next" onClick={()=>g.setReading(value=>Math.min(g.beats.length-1,value+1))}>继续<ArrowRight size={17}/><kbd>空格</kbd></button>:g.finished?<button className="ap-next" onClick={()=>{g.setStory(false);g.setPanel('journal')}}>回看航程<ArrowRight size={17}/></button>:null}</footer>{readAll&&!g.finished&&<div className="ap-choices">{g.choices.map((choice,index)=>{const available=g.narrative?.availableChoiceKeys.includes(choice.choiceKey);return <button key={choice.choiceKey} disabled={g.busy||!available} onClick={()=>g.choose(choice.choiceKey)}><span className="ap-choice-number">{String(index+1).padStart(2,'0')}</span><span>{choice.text}<small>{available?choice.description:choice.unavailableReason}</small></span><ArrowRight size={16}/></button>})}</div>}</section>}
    </>}
    {(g.toast||g.busy&&g.playing)&&<div className="ap-toast" role="status"><Check size={15}/>{g.toast||'正在保存这一步…'}</div>}
    {(g.error||g.playing&&g.store.error)&&<div className="ap-error" role="alert"><span>{g.error||g.store.error}</span><button aria-label="收起错误" onClick={()=>{g.setError('');useAdventureGamePlayerStore.setState({error:''})}}><X size={16}/></button></div>}
    {g.panel&&<Panel title={{map:'甲板地图',journal:'航程日志',saves:'存档与航程',settings:'航程设置'}[g.panel]} onClose={()=>g.setPanel(null)}>{g.panel==='map'&&<StationMap game={g}/>} {g.panel==='journal'&&<Journal game={g}/>} {g.panel==='saves'&&<SavePanel game={g}/>} {g.panel==='settings'&&<><p className="ap-intro">故事时间随剧情推进。你可以慢慢阅读，随时停下。</p>{([{key:'low',title:'轻量画面',note:'降低分辨率，关闭实时阴影'},{key:'fallback',title:'文字探索',note:'以地点导航和剧情对话继续航程'},{key:'fullText',title:'整幕阅读',note:'一次展开本幕全部对话'}] as const).map(item=><label className="ap-toggle" key={item.key}><span>{item.title}<small>{item.note}</small></span><input type="checkbox" checked={g.display[item.key]} onChange={event=>{g.setDisplay(value=>({...value,[item.key]:event.target.checked}));if(item.key==='fallback')g.setNearby(null)}}/></label>)}<button className="ap-text-button" onClick={sound.toggle}>{sound.enabled?'关闭':'开启'}空间站环境音</button><p className="ap-intro">WASD / 方向键移动，Shift 快走，E 交谈，M 打开地图。点击地面行走；右键拖动转向，滚轮调整视距。</p>{g.playing&&<button className="ap-secondary" onClick={()=>{g.setPlaying(false);g.setStory(false);g.setPanel(null)}}>返回标题画面</button>}<p className="ap-credits">原创剧本与程序化场景 · StoryForge<br/>Three.js（MIT） · 可离线游玩，无配音<br/>航程保存在本浏览器，可通过项目备份导出。</p></>}</Panel>}
    {puzzle&&<Panel title={puzzle.title} onClose={()=>g.setPuzzle(null)}><div className="ap-kicker">手动联锁 / 03 STEPS</div><p className="ap-intro">{puzzle.hint}</p><div className="ap-sequence">{[0,1,2].map(index=><span key={index}>{g.sequence[index]==null?'—':puzzle.steps[g.sequence[index]]}</span>)}</div><div className="ap-puzzle-buttons">{puzzle.layout.map(index=><button key={index} disabled={g.busy||g.sequence.includes(index)} onClick={()=>g.solve(index)}>{puzzle.steps[index]}<ChevronRight size={16}/></button>)}</div><p className="ap-puzzle-message" role="status">{g.puzzleMessage}</p><small className="ap-subtle">按正确次序操作。已完成的设备步骤会随存档保留。</small></Panel>}
  </main>
}
